prod:

all:
  handler:
    class:                      fpErrorNotifierHandlerIgnore
    options:                    {ignore_@: false}
        
  message:
    class:                      fpErrorNotifierMessage
    options:                    {}
    
  helper: 
    class:                      fpErrorNotifierMessageHelper
    options:                    {}
    
  decorator:
    class:                      fpErrorNotifierDecoratorHtml
    options:                    {}
  
  driver: 
    class:                      fpErrorNotifierDriverNull
    options:                    {}
#  
# EXAMPLES OF DRIVER CONFIGURATION
#
# FILE DRIVER
#
#  driver:
#    class:                     fpErrorNotifierDriverFile
#    options:        
#      path:                    '%SF_LOG_DIR%/last-error.html'
# 
# OR MAIL NATIVE DRIVER
#
#  driver:
#    class:                     fpErrorNotifierDriverMailNative
#    options:
#      to:                      developer1@example.com,developer2@example.com
#      from:                    mail-from@example.com
#  
#
#  EXAMPLE OF IGNORE HANDLER
#
#  handler:
#    class:                     fpErrorNotifierHandlerIgnore
#    options:
#      ignore_@:                false
#      ignore_errors:           [<?php echo E_ERROR ?>, <?php echo E_NOTICE ?>]
#      ignore_exceptions:       [FooException]
#      ignore_duplication:      true
#      ignore_duplication_time: 3600 # seconds
#      log_ignored:             true